name: GUI

on:
  push:
    branches: [ main, develop ]

  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x ]
    env:
      working-directory: ./gui
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install deps
        working-directory: ${{env.working-directory}}
        run: npm ci

      - name: Build GUI
        working-directory: ${{env.working-directory}}
        run: npm run build

      - name: Store output
        uses: actions/upload-artifact@v2
        with:
          name: gui-dist
          path: ${{env.working-directory}}/dist
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    env:
      working-directory: ./gui
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Download GUI dist data
        uses: actions/download-artifact@v2
        with:
          name: gui-dist
          path: ${{env.working-directory}}/gui/dist

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push GUI
        uses: docker/build-push-action@v2
        with:
          context: ./gui
          push: true
          tags: warmans/rsk-search-gui:latest
