name: Publish

on:
  push:
    branches: [ $default-branch ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Download server binaries
        uses: actions/download-artifact@v2
        with:
          name: server-binaries

      - name: Download server data
        uses: actions/download-artifact@v2
        with:
          name: server-data

      - name: Download GUI dist data
        uses: actions/download-artifact@v2
        with:
          name: gui-dist

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push server
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags: warmans/rsk-search-api:latest

      - name: Build and push GUI
        uses: docker/build-push-action@v2
        with:
          context: ./gui
          push: true
          tags: warmans/rsk-search-gui:latest
