name: Server

on:
  push:
    branches: [ main, develop ]

  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./server
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        working-directory: ${{env.working-directory}}
        run: make build

      - name: Test
        working-directory: ${{env.working-directory}}
        run: go test -v ./...

      - name: Generate files
        working-directory: ${{env.working-directory}}
        run: make init.all generate.plaintext generate.zip

      - name: Store binaries
        uses: actions/upload-artifact@v2
        with:
          name: server-binaries
          path: ${{env.working-directory}}/bin

      - name: Store data files
        uses: actions/upload-artifact@v2
        with:
          name: server-data
          path: |
            ${{env.working-directory}}/var
            !${{env.working-directory}}/var/data/episodes
            !${{env.working-directory}}/var/data/incomplete
            !${{env.working-directory}}/var/data/pending
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    env:
      working-directory: ./server
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Download server binaries
        uses: actions/download-artifact@v2
        with:
          name: server-binaries
          path: ${{env.working-directory}}/bin

      - name: Download server data
        uses: actions/download-artifact@v2
        with:
          name: server-data
          path: ${{env.working-directory}}/var

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push server
        uses: docker/build-push-action@v2
        with:
          context: ./server
          push: true
          tags: warmans/rsk-search-api:latest
